package com.yst.ovls.dao;

import com.yst.ovls.entity.CollectNote;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CollectNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @Delete({
        "delete from collect_note",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @Insert({
        "insert into collect_note (id, user_id, ",
        "note_id, collect_time)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{noteId,jdbcType=INTEGER}, #{collectTime,jdbcType=TIMESTAMP})"
    })
    int insert(CollectNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @InsertProvider(type=CollectNoteSqlProvider.class, method="insertSelective")
    int insertSelective(CollectNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @Select({
        "select",
        "id, user_id, note_id, collect_time",
        "from collect_note",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="note_id", property="noteId", jdbcType=JdbcType.INTEGER),
        @Result(column="collect_time", property="collectTime", jdbcType=JdbcType.TIMESTAMP)
    })
    CollectNote selectByPrimaryKey(Integer id);


    /*
    * @Description：
    * @Author： yanshitong
    * @Date： 2019/3/19 22:46
    * @Param：[userId, noteId]
    * @Return： java.util.List<com.yst.ovls.entity.CollectNote>
    * @Exception： 查看数据库中是否有此条笔记
    */
    @Select({
            "select",
            "id, user_id, note_id, collect_time",
            "from collect_note",
            "where user_id = #{userId,jdbcType=INTEGER} and note_id = #{noteId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
            @Result(column="note_id", property="noteId", jdbcType=JdbcType.INTEGER),
            @Result(column="collect_time", property="collectTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CollectNote> selectByUserIdAndNoteId(Integer userId,Integer noteId);

    /*
    * @Description：
    * @Author： yanshitong
    * @Date： 2019/3/19 16:37
    * @Param：[userId]
    * @Return： java.util.List<com.yst.ovls.entity.CollectNote>
    * @Exception： 通过用户id查询所有收藏笔记
    */
    @Select({
            "select",
            "id, user_id, note_id, collect_time",
            "from collect_note",
            "where user_id = #{userId,jdbcType=INTEGER} ORDER BY collect_time DESC "
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
            @Result(column="note_id", property="noteId", jdbcType=JdbcType.INTEGER),
            @Result(column="collect_time", property="collectTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CollectNote> selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @UpdateProvider(type=CollectNoteSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CollectNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_note
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    @Update({
        "update collect_note",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "note_id = #{noteId,jdbcType=INTEGER},",
          "collect_time = #{collectTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CollectNote record);
}