package com.yst.ovls.entity;

import java.util.Date;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.nickname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.email
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.phone
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.realname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.last_login_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.regist_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String registTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.sex
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Id
     *
     * @return the value of manager.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Id
     *
     * @param id the value for manager.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.nickname
     *
     * @return the value of manager.nickname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.nickname
     *
     * @param nickname the value for manager.nickname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.email
     *
     * @return the value of manager.email
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.email
     *
     * @param email the value for manager.email
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.phone
     *
     * @return the value of manager.phone
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.phone
     *
     * @param phone the value for manager.phone
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.realname
     *
     * @return the value of manager.realname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.realname
     *
     * @param realname the value for manager.realname
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.last_login_time
     *
     * @return the value of manager.last_login_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.last_login_time
     *
     * @param lastLoginTime the value for manager.last_login_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.regist_time
     *
     * @return the value of manager.regist_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.regist_time
     *
     * @param registTime the value for manager.regist_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setRegistTime(String registTime) {
        this.registTime = registTime == null ? null : registTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.sex
     *
     * @return the value of manager.sex
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.sex
     *
     * @param sex the value for manager.sex
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}