package com.yst.ovls.entity;

import java.util.Date;
/** 评价*/
public class Evaluate {
	/**
     * ID
     */
    private Integer id;

    /**
     * 用户ID(外键)
     */
    private Integer useId;

    /**
     * 评价内容
     */
    private String context;

    /**
     * 发表时间
     */
    private Date publishTime;

    /**
     * 视频ID(外键)
     */
    private Integer videoId;

    /**
     * 点赞数
     */
    private Integer likeCount;

    private String videoName;
    private String userName;

    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.id
     *
     * @return the value of evaluate.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.id
     *
     * @param id the value for evaluate.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.use_id
     *
     * @return the value of evaluate.use_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.use_id
     *
     * @param useId the value for evaluate.use_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUseId(Integer useId) {
        this.useId = useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.context
     *
     * @return the value of evaluate.context
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.context
     *
     * @param context the value for evaluate.context
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.publish_time
     *
     * @return the value of evaluate.publish_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.publish_time
     *
     * @param publishTime the value for evaluate.publish_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.video_id
     *
     * @return the value of evaluate.video_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.video_id
     *
     * @param videoId the value for evaluate.video_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.like_count
     *
     * @return the value of evaluate.like_count
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.like_count
     *
     * @param likeCount the value for evaluate.like_count
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}