package com.yst.ovls.entity;

import java.util.Date;
/** 问题回答*/
public class Answer {
	/**
     * ID
     */
    private Integer id;

    /**
     * 回答内容
     */
    private String context;

    /**
     * 发布时间
     */
    private Date publishTime;

    /**
     * 问题ID(外键)
     */
    private Integer issueId;

    /**
     * 用户ID(外键)
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.id
     *
     * @return the value of answer.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.id
     *
     * @param id the value for answer.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.context
     *
     * @return the value of answer.context
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.context
     *
     * @param context the value for answer.context
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.publish_time
     *
     * @return the value of answer.publish_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.publish_time
     *
     * @param publishTime the value for answer.publish_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.issue_id
     *
     * @return the value of answer.issue_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.issue_id
     *
     * @param issueId the value for answer.issue_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.user_id
     *
     * @return the value of answer.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.user_id
     *
     * @param userId the value for answer.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}