package com.yst.ovls.entity;

import java.util.Date;

/** 浏览记录*/
public class BrowsingHistory {
    /**
     * ID
     */
    private Integer id;

    /**
     * 用户ID(外键)
     */
    private Integer useId;

    /**
     * 课程ID(外键)
     */
    private Integer courseId;

    /**
     * 浏览时间
     */
    private Date browseTime;

    /**
     * 视频ID(外键)
     */
    private Integer videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.id
     *
     * @return the value of browsing_history.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.id
     *
     * @param id the value for browsing_history.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.use_id
     *
     * @return the value of browsing_history.use_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.use_id
     *
     * @param useId the value for browsing_history.use_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUseId(Integer useId) {
        this.useId = useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.course_id
     *
     * @return the value of browsing_history.course_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.course_id
     *
     * @param courseId the value for browsing_history.course_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.browse_time
     *
     * @return the value of browsing_history.browse_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getBrowseTime() {
        return browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.browse_time
     *
     * @param browseTime the value for browsing_history.browse_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setBrowseTime(Date browseTime) {
        this.browseTime = browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.video_id
     *
     * @return the value of browsing_history.video_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.video_id
     *
     * @param videoId the value for browsing_history.video_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
}