package com.yst.ovls.entity;

/** 方向*/
public class Direction {
    /**
     * ID(主键)
     */
    private Integer id;

    /**
     * 名称(not null)
     */
    private String name;

    /**
     * 顺序
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.id
     *
     * @param id the value for direction.id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direction.name
     *
     * @return the value of direction.name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.name
     *
     * @param name the value for direction.name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}