package com.yst.ovls.entity;

import java.util.Date;

public class NoteLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.note_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_like.like_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Date likeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.Id
     *
     * @return the value of note_like.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.Id
     *
     * @param id the value for note_like.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.user_id
     *
     * @return the value of note_like.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.user_id
     *
     * @param userId the value for note_like.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.note_id
     *
     * @return the value of note_like.note_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.note_id
     *
     * @param noteId the value for note_like.note_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_like.like_time
     *
     * @return the value of note_like.like_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getLikeTime() {
        return likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_like.like_time
     *
     * @param likeTime the value for note_like.like_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }
}