package com.yst.ovls.entity;

import java.util.Date;

public class PaperExamRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.record_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.paper_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.answer
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_record.create_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.record_id
     *
     * @return the value of paper_exam_record.record_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.record_id
     *
     * @param recordId the value for paper_exam_record.record_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.user_id
     *
     * @return the value of paper_exam_record.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.user_id
     *
     * @param userId the value for paper_exam_record.user_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.paper_id
     *
     * @return the value of paper_exam_record.paper_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.paper_id
     *
     * @param paperId the value for paper_exam_record.paper_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.question_id
     *
     * @return the value of paper_exam_record.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.question_id
     *
     * @param questionId the value for paper_exam_record.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.answer
     *
     * @return the value of paper_exam_record.answer
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.answer
     *
     * @param answer the value for paper_exam_record.answer
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_record.create_time
     *
     * @return the value of paper_exam_record.create_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_record.create_time
     *
     * @param createTime the value for paper_exam_record.create_time
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}