package com.yst.ovls.entity;
/** 试题选项*/
public class QuestionOptions {
    /**
     * 选项ID
     */
    private Integer optionId;

    /**
     * 试题ID(唯一性约束)
     */
    private Integer questionId;

    /**
     * 选项内容
     */
    private String optionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_id
     *
     * @return the value of question_options.option_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_id
     *
     * @param optionId the value for question_options.option_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.question_id
     *
     * @return the value of question_options.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.question_id
     *
     * @param questionId the value for question_options.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_name
     *
     * @return the value of question_options.option_name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_name
     *
     * @param optionName the value for question_options.option_name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }
}