package com.yst.ovls.entity;
/** 试题和知识点*/
public class QuestionKnowledge {
    /**
     * id
     */
    private Integer id;

    /**
     * 考题id(唯一性约束)
     */
    private Integer questionId;

    /**
     * 知识点id
     */
    private Integer knowledgeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.Id
     *
     * @return the value of question_knowledge.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.Id
     *
     * @param id the value for question_knowledge.Id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.question_id
     *
     * @return the value of question_knowledge.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.question_id
     *
     * @param questionId the value for question_knowledge.question_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.knowledge_id
     *
     * @return the value of question_knowledge.knowledge_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.knowledge_id
     *
     * @param knowledgeId the value for question_knowledge.knowledge_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }
}