package com.yst.ovls.entity;

/** 试题类型*/
public class QuestionType {
    /**
     * 试题类型id
     */
    private Integer typeId;

    /**
     * 试题类型名
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.type_id
     *
     * @return the value of question_type.type_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.type_id
     *
     * @param typeId the value for question_type.type_id
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_type.type_name
     *
     * @return the value of question_type.type_name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_type.type_name
     *
     * @param typeName the value for question_type.type_name
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}