server:
 port: 9529
spring:
 datasource:
  username: root
  password: 123
  url: jdbc:mysql://localhost:3306/ovls?useUnicode=true&characterEncoding=utf8
  driverClassName: com.mysql.jdbc.Driver
 application:
  name: ovls-evaluateAndNote
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7777/eureka
 instance:
  perferIpAddress: true
  instanceId: ${spring.cloud.client.ip-address}:${server.port}