package com.yst.ovls.entity;

import java.util.Date;

/** 课程 */
public class Course {
	/**
	 * ID(主键)
	 */
	private Integer id;

	/**
	 * 课程名
	 */
	private String name;

	/**
	 * 课程简介
	 */
	private String intro;

	/**
	 * 学习人数
	 */
	private Integer learnCount;

	/**
	 * 难度
	 */
	private String difficulty;

	/**
	 * 课程评分
	 */
	private Integer score;

	/**
	 * 课程图片地址
	 */
	private String image;

	/**
	 * 课程发布时间
	 */
	private Date publishTime;

	/**
	 * 课程价格
	 */
	private Integer price;

	/**
	 * 学科ID(外键，表subject)
	 */
	private Integer subjectId;
	private String subjectName;

	/**
	 * 方向ID(外键，表direction)
	 */
	private Integer directionId;
    private String directionName;

	/**
	 * 课程时长(小时)
	 */
	private Integer learnTime;

	public String getSubjectName(){
	    return subjectName;
    }
    public String getDirectionName(){
	    return directionName;
    }

	@Override
	public String toString() {
		return "Course [id=" + id + ", name=" + name + ", intro=" + intro + ", learnCount=" + learnCount
				+ ", difficulty=" + difficulty + ", score=" + score + ", image=" + image + ", publishTime="
				+ publishTime + ", price=" + price + ", subjectId=" + subjectId + ", directionId=" + directionId
				+ ", learnTime=" + learnTime + "]";
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.id
	 *
	 * @return the value of course.id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.id
	 *
	 * @param id
	 *            the value for course.id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.name
	 *
	 * @return the value of course.name
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.name
	 *
	 * @param name
	 *            the value for course.name
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.intro
	 *
	 * @return the value of course.intro
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.intro
	 *
	 * @param intro
	 *            the value for course.intro
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.learn_count
	 *
	 * @return the value of course.learn_count
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getLearnCount() {
		return learnCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.learn_count
	 *
	 * @param learnCount
	 *            the value for course.learn_count
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setLearnCount(Integer learnCount) {
		this.learnCount = learnCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.difficulty
	 *
	 * @return the value of course.difficulty
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public String getDifficulty() {
		return difficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.difficulty
	 *
	 * @param difficulty
	 *            the value for course.difficulty
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setDifficulty(String difficulty) {
		this.difficulty = difficulty == null ? null : difficulty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.score
	 *
	 * @return the value of course.score
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.score
	 *
	 * @param score
	 *            the value for course.score
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.image
	 *
	 * @return the value of course.image
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.image
	 *
	 * @param image
	 *            the value for course.image
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.publish_time
	 *
	 * @return the value of course.publish_time
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Date getPublishTime() {
		return publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.publish_time
	 *
	 * @param publishTime
	 *            the value for course.publish_time
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.price
	 *
	 * @return the value of course.price
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.price
	 *
	 * @param price
	 *            the value for course.price
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.subject_id
	 *
	 * @return the value of course.subject_id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.subject_id
	 *
	 * @param subjectId
	 *            the value for course.subject_id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.direction_id
	 *
	 * @return the value of course.direction_id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getDirectionId() {
		return directionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.direction_id
	 *
	 * @param directionId
	 *            the value for course.direction_id
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setDirectionId(Integer directionId) {
		this.directionId = directionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.learn_time
	 *
	 * @return the value of course.learn_time
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public Integer getLearnTime() {
		return learnTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.learn_time
	 *
	 * @param learnTime
	 *            the value for course.learn_time
	 *
	 * @mbg.generated Mon Jan 07 11:58:20 CST 2019
	 */
	public void setLearnTime(Integer learnTime) {
		this.learnTime = learnTime;
	}
}