package com.yst.ovls.dao;

import com.yst.ovls.entity.QuestionType;
import org.apache.ibatis.jdbc.SQL;

public class QuestionTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String insertSelective(QuestionType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("question_type");
        
        if (record.getTypeId() != null) {
            sql.VALUES("type_id", "#{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getTypeName() != null) {
            sql.VALUES("type_name", "#{typeName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbg.generated Mon Jan 07 11:58:20 CST 2019
     */
    public String updateByPrimaryKeySelective(QuestionType record) {
        SQL sql = new SQL();
        sql.UPDATE("question_type");
        
        if (record.getTypeName() != null) {
            sql.SET("type_name = #{typeName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("type_id = #{typeId,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}